apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: roboshop
  labels: #these are deployment labels
    purpose: ingress-demo
    project: roboshop
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels: #these labels are used to select pods
      purpose: ingress-demo
      project: roboshop
      app: app1
  template: #pod definition
    metadata:
      labels:
        purpose: ingress-demo
        project: roboshop
        app: app1
    spec:
      containers:
      - name: app1
        image: pravakula/app1:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: app1
spec:
  selector:
    purpose: ingress-demo
    project: roboshop
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
